import PropTypes from 'prop-types';

function Course(props) {

  function BuyCourse(discount,e){
    console.log(props.course,"Purchased with",discount,"% discount");
    console.log(e)
  }

  return (
    // Content Filtering using Logical Operator
    props.course && <div className="card">
      <img src={props.img}></img>
      <h3>{props.course}</h3>
      <p>{props.o_price}</p>
      <label>{props.n_price}</label>
      <br />
      <span>{props.rating}</span>
      {/* Basic function call */}
      {/* <button onClick={BuyCourse}>Buy Now</button> */}

      {/* Function call with arguements
      event is generated by the event which contains the details of the event
      Here () => arrow function is used to call a function with parameters,since directly writing the function will make a function call
      the following is a multi-line arrow function 
      (event) => {BuyCourse(20,event);console.log(event)}
      */}
      <button onClick={(event) => {BuyCourse(20,event);console.log(event)}}>Buy Now</button>
    </div>
  );
}

Course.PropTypes = {
  img: PropTypes.string,
  course: PropTypes.string,
  o_price: PropTypes.string,
  n_price: PropTypes.int,
  rating: PropTypes.string,
  show: PropTypes.bool,
};

export default Course;
