import PropTypes, { func } from 'prop-types';
import { useState } from 'react';

function Course(props) {

  // Using Hooks
  const [purchased,setPurchased] = useState(false);
  const [applydiscount,setDiscount] = useState(false);


  function BuyCourse(discount){
    console.log(props.course,"Purchased with",discount,"% discount");
    setPurchased(true);

  }
  function Applydiscount(discount){
    setDiscount(true);
  }

  return (
    // Content Filtering using Logical Operator
    props.course && <div className="card">
      <img src={props.img}></img>
      <h3>{props.course}</h3>
      <button onClick={() => Applydiscount(20)}>Apply Discount</button>
      {/* <p>{props.o_price}</p> */}
      <label>{applydiscount ? "$"+props.n_price : props.o_price}</label>
      <br />
      <span>{props.rating}</span>
      {/* Basic function call */}
      {/* <button onClick={BuyCourse}>Buy Now</button> */}

      {/* Function call with arguements
      event is generated by the event which contains the details of the event
      Here () => arrow function is used to call a function with parameters,since directly writing the function will make a function call
      the following is a multi-line arrow function 
      (event) => {BuyCourse(20,event);console.log(event)}
      */}
      <button onClick={() => BuyCourse(20)}>{purchased ? "Purchased" : "Buy Now"}</button>
      <button onClick={props.handle_delete}>Delete</button>
    </div>
  );
}

Course.PropTypes = {
  img: PropTypes.string,
  course: PropTypes.string,
  o_price: PropTypes.string,
  n_price: PropTypes.int,
  rating: PropTypes.string,
  show: PropTypes.bool,
};

export default Course;
